name: Deploy production(xtoken-home)

on:
  push:
    tags:
      - "home-*"

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  deploy-website:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: darwinia-network/devops
          path: .github

      - uses: ./.github/actions/smart-vercel
        name: Deploy xtoken-home
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          script_install: npm i
          script_build: npm run build -w xtoken-home
          dist_path: packages/xtoken-home/out
          project_name: xtoken-home
          alias_domain: "xtoken-home-prd"
          prod_mode: true
          enable_cache: true
          enable_notify_comment: true
          enable_notify_slack: true
          slack_channel: helixbox-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
