name: Deploy production(xtoken-ui)

on:
  push:
    tags:
      - "ui-*"

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: darwinia-network/devops
          path: .github

      - uses: ./.github/actions/smart-vercel
        name: Deploy xtoken-ui (mainnet)
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          script_run: false
          dist_path: packages/xtoken-ui
          project_name: xtoken-ui
          alias_domain: "xtokenui-prd-main"
          prod_mode: true
          enable_cache: true
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: ./.github/actions/smart-vercel
        name: Deploy xtoken-ui (testnet)
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          script_run: false
          dist_path: packages/xtoken-ui
          project_name: xtoken-ui-test
          alias_domain: "xtokenui-prd-test"
          prod_mode: true
          enable_cache: true
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
