name: Deploy develop(xtoken-ui)

on:
  pull_request:
    paths:
      - "packages/xtoken-ui/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: darwinia-network/devops
          path: .github

      - uses: ./.github/actions/smart-vercel
        name: Deploy xtoken-ui (mainnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          project_name: xtoken-ui
          alias_domain: "xtokenui-dev-mainnet"
          script_install: npm i
          script_build: npm run build:mainnet -w xtoken-ui
          dist_path: packages/xtoken-ui/dist
          enable_notify_comment: true
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: ./.github/actions/smart-vercel
        name: Deploy xtoken-ui (testnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          script_install: npm i
          script_build: npm run build:testnet -w xtoken-ui
          dist_path: packages/xtoken-ui/dist
          project_name: xtoken-ui-test
          alias_domain: "xtokenui-dev-testnet"
          enable_cache: true
          enable_notify_comment: true
<<<<<<< HEAD
=======
          enable_notify_slack: false
          slack_channel: helixbox-ui
>>>>>>> main
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
